### PR TITLE
SSL: fix MLP head and remove L2 normalization

### LINKED ISSUE #138: Hard-coded stem stride in `ContrastiveEncoder`
Currently the `stem_stride` parameter is not used and the stem stride will be the same (5, 4, 4) regardless of the kernel size. There is also no way to specify the stride from the lightning module (and the config).

This was due to a incomplete refactor in #130.

### LINKED ISSUE #139: Update the projection head (normalization and size).
TL;DR: current projection head doesn't do what it is supposed to do. It should have a batch norm and the size of the features and projections may be reduced further.
In the previous implementations of contrastive learning models (`dynacontrast`), we used batch norm in the projection head after each MLP.
```
(projection): Sequential(
    (fc1): Linear(in_features=2048, out_features=2048, bias=False)
    (bn1): BatchNorm1d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu1): ReLU()
    (fc2): Linear(in_features=2048, out_features=128, bias=False)
    (bn2): BatchNorm1dNoBias(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
```

This [paper](https://arxiv.org/pdf/2212.11491) also recommends using a non-linear projection head with batch norm. Different projection heads are evaluated by comparing the rank of the features (# of independent features) before and after the projection head:
image

As expected, the rank(projections) << rank(features). 

[Our current model's behavior](https://github.com/mehta-lab/VisCy/tree/cbf280f445a3675a3b82a298cdf873935700b894) is the opposite: rank(projections)> rank(features) as seen from the examination of the principal components in each.

image

This seems to be the consequence of clipping of projections, which seems to be due to the use of ReLU without normalization.

`plt.plot(np.mean(embedding_dataset["projections"].values,axis=1))` 
image

`plt.plot(np.std(embedding_dataset["projections"].values,axis=1))`
image

### PR DESCRIPTION
**Pull request by mattersoflight**
Fix the sequence of batchnorm and linear in the last MLP layer of the contrastive encoder model.

Remove L2 normalization before computing triplet loss. This works best when also reducing the dimension of projections.

Refactor `light` module into `representation` and `translation` to separate pipelining code for different tasks.

Fix #139, fix #138.

### CODE REVIEW

**Comment by mattersoflight** [comment]
@ziw-liu started the draft. I'll let you complete it. Feel free to make other improvements in architecture as you go.

**Comment by Soorya19Pradeep** [comment]
@ziw-liu , I get the following error:

> [rank3]:     else self._run_ddp_forward(*inputs, **kwargs)
> [rank3]:   File "/hpc/mydata/soorya.pradeep/scratch/viscy_test/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1454, in _run_ddp_forward
> [rank3]:     return self.module(*inputs, **kwargs)  # type: ignore[index]
> [rank3]:   File "/hpc/mydata/soorya.pradeep/scratch/viscy_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
> [rank3]:     return self._call_impl(*args, **kwargs)
> [rank3]:   File "/hpc/mydata/soorya.pradeep/scratch/viscy_test/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
> [rank3]:     return forward_call(*args, **kwargs)
> [rank3]:   File "/hpc/mydata/soorya.pradeep/scratch/viscy_test/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 633, in wrapped_forward
> [rank3]:     out = method(*_args, **_kwargs)
> [rank3]:   File "/hpc/mydata/soorya.pradeep/scratch/viscy_infection_phenotyping/VisCy/viscy/representation/engine.py", line 144, in validation_step
> [rank3]:     self._log_metrics(
> [rank3]:   File "/hpc/mydata/soorya.pradeep/scratch/viscy_infection_phenotyping/VisCy/viscy/representation/engine.py", line 74, in _log_metrics
> [rank3]:     cosine_sim_pos = F.cosine_similarity(anchor, positive, dim=1).mean()
> [rank3]: IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
> 
> Sanity Checking: |          | 0/? [00:00<?, ?it/s]
> Sanity Checking:   0%|          | 0/2 [00:00<?, ?it/s]
> Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]srun: error: gpu-f-2: tasks 0,2: Exited with exit code 1
> srun: error: gpu-f-2: task 3: Exited with exit code 1

**Comment by ziw-liu** [comment]
@Soorya19Pradeep Fixed in https://github.com/mehta-lab/VisCy/pull/141/commits/11fa65a1ce0e3717fbec80d41f553044cde5bdb3. This is still very much work in progress. I have not trained a full model yet.

**Comment by ziw-liu** [comment]
@mattersoflight With batch normalization in the MLP head, the features still have much lower rank (11) than projection (96).

This also shows in PCA:

image

**Comment by mattersoflight** [comment]
@ziw-liu our next steps:
* Reorder batchnorm layer and MLP layer at the network's end (MLP->batchnorm).
* Do not L2-normalize projections during fitting, let the optimizer enforce normalization. 
* Perform two computational experiments: with the above changes with projection dim = 128 and projection dim ~ 16.

**Pull request closed without merging**
