### PR TITLE
Project icon

### PR DESCRIPTION
**Pull request by ziw-liu**
This is a proposal to create a icon for the project.

@mattersoflight and I had an offline discussion. Some ideas were:
- encode-decoder architecture
- images of cells undergoing transforms

Here I'm materializing these ideas in a very simple (and rudimentary) form. Also trying to adhere to the Biohub style guide (with colors and the usage of line-connected circles). This first draft features:
- encode-decoder schematic
- circular structures resembling (very abstract) cellular compartments
- subsets of the connecting lines can form characters in the project name (with some imagination of a Phoenician font)

Created with Inkscape. Suggestions and edits are welcome!

Some rendered theme variants (light, dark, cyan):

image

image

image

### CODE REVIEW

**Comment by mattersoflight** [comment]
It will be good to include cells in the logo. I suggest something like this: 
image

It hints at the ability of VisCy to find single cells and enable their phenotyping (i.e., dimensionality reduction). For a number of reasons that we should discuss off-line, I think porting [representation learning with contrastive loss](https://github.com/mehta-lab/dynacontrast) would be next appropriate type of model for us to incorporate in VisCy.

**Comment by ziw-liu** [comment]
> It hints at the ability of VisCy to find single cells and enable their phenotyping (i.e., dimensionality reduction).

This is a nice concept, and is great for a graphical summary or social media preview. I've been thinking about 'icon' in a slightly different context, mainly in a much smaller size. I wanted it to be still recognizable at 32x32 px (favicon size) so it can be used for places like GH thumbnails and docs site favicons.

**Comment by edyoshikun** [comment]
I like the idea of a 32x32px favicon size and trying to keep it simple. I think we can combine both of the ideas above while still keeping it as 'minimalistic' as possible. [](url)
Screenshot 2023-08-23 at 12 00 31 AM 

Also, another option could be to replace the circles in your original design with more like 'cell' like structures (polygon with nucleus, oval with nucleus) and that would show some of the cell phenotyping and image translation.

**Comment by edyoshikun** [comment]
Ignore the colors I am using, but here is another option. 
Screenshot 2023-08-23 at 12 09 02 AM

**Comment by mattersoflight** [comment]
Good idea @edyoshikun! I like your variant of favicon that slightly curves the lines in @ziw-liu's original design to indicate a cell.  @ziw-liu, yes let's reserve the larger cartoon for social media image. Please make one with biorender.

**Comment by ziw-liu** [comment]
@edyoshikun I made some edits according to your suggestion:

diagonal-edge
diagonal-fill
all-edge
all-fill
diag-reverse-fill
all-no-line-fill

**Comment by edyoshikun** [comment]
I am between 1,4 and 6.

**Comment by mattersoflight** [comment]
Thanks @ziw-liu. The favicons do suggest nuclei and plasma membrane! I vote for the 6th one: [this](https://user-images.githubusercontent.com/67518483/267800882-a54bfac9-62e7-4bac-8e4e-10d86af43640.png).

**Comment by ziw-liu** [comment]
Now I think 6 looks too symmetrical (i.e. like a cross) when enlarged... I'm in for 1, 5, and 7.

**Comment by edyoshikun** [comment]
Let's do 5!

**Review by edyoshikun — APPROVED** [review]
Thank you! @ziw-liu looks great.

**Pull request merged**
