### PR TITLE
UMAP line plot to assess temporal smoothness in features space

### PR DESCRIPTION
**Pull request by ziw-liu**
Also reduce the UMAP components in `viscy.representation.evaluation.compute_umap()` to 2.

### CODE REVIEW

**Comment by Soorya19Pradeep** [comment]
@ziw-liu , I was able to use the scripts to generate the figures. I just needed to pip install 'cmap' into my environment.

**Comment by ziw-liu** [comment]
> I just needed to pip install 'cmap' into my environment.
It's part of the `visual` optional dependencies.

**Comment by Soorya19Pradeep** [comment]
Thanks @ziw-liu !

**Review by Soorya19Pradeep — COMMENTED** [review]
The script works well for me

**Pull request merged**
