### PR TITLE
Add badges to readme

### PR DESCRIPTION
**Pull request by ziw-liu**
Add badges for:

- PyPI stable version
- PyPI monthly downloads
- PyPI total downloads
- GitHub contributors
- GitHub stars
- GitHub forks
- SPEC 0 adoption (placeholder for supported python versions)

### CODE REVIEW

**Comment by mattersoflight** [comment]
LGTM @ziw-liu! Please also add badges for:
- total downloads via PyPI
- contributors
- forks
- stars
- supported versions of python

**Comment by ziw-liu** [comment]
> supported versions of python

The classifier metadata needs to be explicitly added and then released to PyPI. Currently it will error like this: PyPI - Python Version

I added those classifiers, and can add the badge after v0.3.0 stable is released.

**Review by mattersoflight — APPROVED** [review]
Approving so you can merge after adding the other badges.

**Comment by ziw-liu** [comment]
> total downloads via PyPI

The only available quantities are day, week, and month: https://pypistats.org/packages/viscy

**Comment by ziw-liu** [comment]
>forks
stars

Why do we need these in the README? GitHub already shows them in the repos's home page.

**Comment by mattersoflight** [comment]
> The only available quantities are day, week, and month: https://pypistats.org/packages/viscy

I got the idea from waveOrder README, which I see fetches the stats from pepy (https://www.pepy.tech/projects/waveorder, https://www.pepy.tech/projects/viscy)


We should have badges on all our repos: cc: @talonchandler, @ieivanov

**Comment by mattersoflight** [comment]
> forks
> stars

Make it easier to find the info. These numbers are summarized in reports.

**Pull request merged**
