### PR TITLE
GMM clustering and fixed compute pca

### PR DESCRIPTION
**Pull request by alishbaimran**
- [x] added GMMClustering class w/ various methods for GMM clustering using BIC and AIC 
- [x] fixed compute_pca so values aren't hardcoded 
- [x] example script to run gmm clustering w/ ground truth annotations 
- [x] visualizing Feb + June datasets using UMAPs colored by GMM cluster weights and by predicted cluster labels

### CODE REVIEW

**Comment by mattersoflight** [comment]
@alishbaimran @Soorya19Pradeep I am booked with multiple planning and writing projects through the end of the year. I  think Soorya is situated to provide a solid review and testing of this code. She implemented GMM clustering over time for infection state discrimination for Fig. 5 of https://academic.oup.com/pnasnexus/article/3/9/pgae323/7731083

**Comment by Soorya19Pradeep** [comment]
@alishbaimran , can you pull the changes from the representation branch into this branch? There seem to be some conflicts with the representation branch.

**Comment by alishbaimran** [comment]
> @alishbaimran , can you pull the changes from the representation branch into this branch? There seem to be some conflicts with the representation branch.

Yes I can do this and then push changes again.

**Comment by mattersoflight** [comment]
@alishbaimran it looks like you have merged the changes from `representation` in way that creates unnecessary diffs.  
You may need to do this:
1. start a new branch from `representation`
2. transfer the relevant files by hand from this branch.
3. open a fresh PR and close this one.

**Comment by Soorya19Pradeep** [comment]
@alishbaimran , as you open the new branch to make the changes Shalin mentioned please keep in mind to clean up the scripts like [this](https://github.com/mehta-lab/VisCy/blob/main/applications/contrastive_phenotyping/figures/figure_4a_1.py) inside `applications/contrastive_phenotyping/figures` folder as these doesn't make sense anymore.

**Comment by alishbaimran** [comment]
> @alishbaimran , as you open the new branch to make the changes Shalin mentioned please keep in mind to clean up the scripts like [this](https://github.com/mehta-lab/VisCy/blob/main/applications/contrastive_phenotyping/figures/figure_4a_1.py) inside `applications/contrastive_phenotyping/figures` folder as these doesn't make sense anymore.

@Soorya19Pradeep I'm not sure if these scripts are even suppose to be included in new branch. I pulled the files that were pushed to this branch and it seems some really old commits were moved here?
Screenshot 2024-10-21 at 11 37 39 AM

@mattersoflight could you clarify if/what to do with these olds commits?

**Comment by Soorya19Pradeep** [comment]
@alishbaimran , I think it is best to close this and start a new branch. Let us do that and then you can add the new scripts for GMM clustering and remove those figure scripts there.

**Pull request closed without merging**
